<a href="https://colab.research.google.com/github/Bob299-bob/NLL-natural-language-processing-/blob/main/self_attention0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
import math
l,d_k,d_v=4,8,8
q=np.random.randn(l,d_k)
k=np.random.randn(l,d_k)
v=np.random.randn(l,d_v)
print("Q\n",q)
print("k\n",k)
print("v\n",v)

Q
 [[ 8.38845726e-01 -4.81504610e-01  5.73191457e-01  2.11234863e+00
  -1.84345872e+00  1.18120469e-01 -6.15267281e-01 -2.54464693e+00]
 [-1.14928684e+00  5.17977909e-01  5.06621512e-01  5.24435990e-01
  -1.01210127e+00 -8.40819200e-01  1.41069155e+00 -4.10053418e-01]
 [-1.13400613e-01 -5.78694280e-01  2.96250934e-01  7.57852249e-01
  -1.18934252e-01  6.00408087e-02  1.75050663e-01 -4.23889502e-02]
 [ 1.58024830e-01  1.06199131e-04 -1.97478501e-01 -5.20431430e-01
   3.45827989e-02  8.75537810e-01 -1.50279477e+00  1.72229801e+00]]
k
 [[ 0.5367691  -0.08316988  0.32328321  1.84408085 -0.14158785  0.85856096
   1.23989639 -0.33443596]
 [-0.93916735  0.55969623 -0.07064675  3.20466638 -1.40489636  0.95329747
  -0.17036299  1.40396921]
 [ 0.26567382 -0.23939827  0.24248819 -0.0999104   0.05171373 -0.64362389
  -0.94303913 -0.70275003]
 [ 1.02222347 -0.89483479 -0.65100237  0.59666807  0.71178612  1.72012423
   0.81644616  0.94556134]]
v
 [[ 1.1165428   0.89675836  0.5019294   0.96622162  1.

   
    self attention = softmax((Q.k^t/sqrt(d_k))+M)V

In [57]:
np.matmul(q, k.T)

array([[ 5.02153672,  4.90625092,  2.46319181, -1.84184197],
       [ 1.77855743,  2.81844875, -0.9122258 , -3.0579203 ],
       [ 1.78018317,  2.32533572, -0.07555415,  0.78270118],
       [-2.63124722,  1.65792651, -0.3088114 ,  1.91171256]])

Where matmul() is used to perform the matrix multiplication.

In [58]:
q.var(),k.var(),np.matmul(q,k.T).var()

(np.float64(0.9168096196173193),
 np.float64(0.9092649357189566),
 np.float64(5.337072481997458))

In [59]:
from typing import KeysView
scaled = np.matmul(q, k.T) / math.sqrt(d_k)
q.var(),k.var(),scaled.var()

(np.float64(0.9168096196173193),
 np.float64(0.9092649357189566),
 np.float64(0.6671340602496822))

In [60]:
scaled

array([[ 1.77538133,  1.73462165,  0.87086982, -0.65118947],
       [ 0.62881501,  0.99647211, -0.32252052, -1.08113809],
       [ 0.6293898 ,  0.82213033, -0.02671243,  0.27672666],
       [-0.93028637,  0.58616554, -0.10918132,  0.67589246]])

In [61]:
mask=np.tril(np.ones((l,l)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [62]:
mask[mask == 0] = np.inf
mask[mask == 1] = 0

In [64]:
mask

array([[ 0., inf, inf, inf],
       [ 0.,  0., inf, inf],
       [ 0.,  0.,  0., inf],
       [ 0.,  0.,  0.,  0.]])

In [30]:
scaled + mask

array([[ 2.49816193,         inf,         inf,         inf],
       [ 1.4429706 , -0.83135241,         inf,         inf],
       [-0.86579545,  0.85832841,  2.08518427,         inf],
       [-2.68412418,  0.41549876,  0.09782384,  0.96882533]])

In [33]:
def softmax(x):
  return (np.exp(x).T / np.sum(np.exp(x),axis=-1)).T

In [ ]:
attention = softmax(scaled + mask)

In [37]:
attention

array([[0.        ,        nan,        nan,        nan],
       [0.        , 0.        ,        nan,        nan],
       [0.        , 0.        , 0.        ,        nan],
       [0.0128323 , 0.2847434 , 0.20724745, 0.49517685]])

In [48]:
new_v = np.matmul(attention, v)
new_v

array([[        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan],
       [-0.11578572,  0.60796381, -0.37483162,  0.51935018,  0.38996692,
         0.18637581,  0.71736705,  0.36109767]])

In [42]:
v

array([[ 0.42866258,  0.82167657,  0.43085147, -2.05467844, -0.09052551,
        -0.98940962, -0.69436987, -0.71922652],
       [-0.03151219, -1.3320934 ,  1.58825816,  2.31884575,  0.00839278,
         2.54894556,  1.17091545, -1.90869296],
       [-0.08257851,  0.41376524, -1.25621323, -1.09408122, -0.48929809,
         1.14154013, -0.3143581 , -0.77694268],
       [-0.19225328,  1.79930223, -1.15566684,  0.22655737,  0.9898374 ,
        -1.54147852,  0.92495617,  2.17060652]])